### ISSUE TITLE
Model O, what's the syntax for --set-effect?

### ISSUE THREAD

**Issue by GabMus** [enkore/gloriousctl#1]
I've tried with `off` `glorious` and `static`, the effect doesn't seem to change. I'm pretty sure I'm just missing the syntax. Feel free to ask anything that could help.

**Comment by enkore** [comment]
Not implemented yet :grin:

**Comment by enkore** [comment]
Implemented now, details in the readme.

Example: `./gloriousctl --set-effect single --set-colors 00FF00`
`./gloriousctl --set-effect breathing7 --set-brightness 2 --set-speed 3 --set-colors FF0000,00FF00,0000FF,FFFF00,00FFFFF,FF00FF,FFFFFF`

**Comment by GabMus** [comment]
Awesome, thanks!
