### ISSUE TITLE
Issue when compiling (linker command failing)

### ISSUE THREAD

**Issue by KyngK** [enkore/gloriousctl#10]
Hi, I'm having an issue when compiling the code using the makefile:

`ld: library not found for -lhidapi-hidraw
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [gloriousctl] Error 1`

I installed hidapi, and I've searched all over the internet but I cannot find anything that helps, even remotely. Does someone know why this is failing?

**Comment by enkore** [comment]
There's two implementations of hidapi, a portable libusb-based one (which requires exclusive device access, so not great here) and the hidraw (Linux-only) version. Make sure you install the hidraw variant of hidapi. What distro is this?

**Comment by KyngK** [comment]
Ah that must have been the problem... I was trying to compile this for MacOS

**Comment by enkore** [comment]
You'd have to edit the Makefile to link against the libusb variant instead, and then find a way to detach the mouse from the normal mouse driver so that the application can attach to it using libusb. Dunno how you can do that on mac.

**Comment by KyngK** [comment]
Yeah, that's going to be too hard for me since I don't know C. Do you know if libratbag has support for the model o? I originally came here from an issue in their repository.

**Comment by enkore** [comment]
Yeah

**Comment by KyngK** [comment]
Alright, I'll try that out. Thanks!
