### ISSUE TITLE
Does this support changing bindings of buttons?

### ISSUE THREAD

**Issue by allusive-dev** [enkore/gloriousctl#17]
Im using a Glorious Model D Wireless and want to know if I can rebind the side and top buttons?

**Comment by staticssleever668** [comment]
Hi, Model D Wireless is a completely different device from Model D.
There is a similar utility that does support wireless Glorious mice and seem to have support for rebinding buttons (fork of Model O-only mow - mxw): https://github.com/dxbednarczyk/mxw.
Anyway, gloriousctl does not support button rebinding on the regular Model D, however, libratbag does: https://github.com/libratbag/libratbag.
