### ISSUE TITLE
Debounce timer not working correctly

### ISSUE THREAD

**Issue by oTerminal** [enkore/gloriousctl#4]
As you can see in the video I uploaded below, after the left click, I started drag clicking on my rmb and I got only 1 cps. But just double clicking with my finger yields 2 cps. 
https://user-images.githubusercontent.com/70430883/128612703-705842e6-ba13-4f01-8a79-6f718ab53741.mp4

**Comment by oTerminal** [comment]
I don't know how to properly explain this but I think it only detects it every second so I can't reach above 2 or 3 cps.

**Comment by staticssleever668** [comment]
Hi, do I understand correctly that some of your clicks don't get recognized? If so, I get such behavior only when I set the timer to 100 ms or so, but we limit it to 16 ms here. What value did you set the timer to? In your USB packet dump I can see you setting it to 8 and 16 milliseconds, did you try using such values?

**Comment by oTerminal** [comment]
I set it to 4 now, in my usb dump I kept setting it to 4, 8, 10 etc multiple debounce times.

**Comment by fschaap** [comment]
Just chipping in to mention that I set debounce to 4 and my son happily reports that it works for him. Piper doesn't yet offer a way to set debounce, so it's nice this works.

Parameters: Model O/Manjaro/kernel 6.3/piper (0.7-1) & libratbag (0.17-1) from community repos
