### ISSUE TITLE
Support for Model O Wireless with product id 2011

### ISSUE THREAD

**Issue by mjog** [enkore/gloriousctl#5]
I just got a Model O wireless and was trying this out. I was able to get teh device recognised using this patch:

```
diff --git a/gloriousctl.c b/gloriousctl.c
index e9b6e76..7897230 100644
--- a/gloriousctl.c
+++ b/gloriousctl.c
@@ -34,6 +34,7 @@ static struct supported_device supported_devices[] = {
     { .vid = 0x258a, .pid = 0x27, .name =  "Dream Machines DM5" },
     { .vid = 0x258a, .pid = 0x33, .name =  "Glorious Model D" },
     { .vid = 0x258a, .pid = 0x36, .name =  "Glorious Model O/O-" }, // probably works
+    { .vid = 0x258a, .pid = 0x2011, .name =  "Glorious Model O Wireless" }, // probably works
 };
 
 #pragma pack(push, 1)
```

But setting doesn't seem to work. E.g after running:

```
mjog@ridefort:~/.local/src/gloriousctl$ sudo ./gloriousctl --set-effect off
Detected Glorious Model O Wireless
Opening device /dev/hidraw4
131
read firmware version: Success
mjog@ridefort:~/.local/src/gloriousctl$ 
```

The mouse is still doing its rainbow thing.

**Comment by mjog** [comment]
Anything I can do to help debug this?

**Comment by nistvan86** [comment]
There's another Linux utility for Glorious mice, and someone else requested the wireless compatibility. As it turned out, the protocol used is completely different. https://github.com/libratbag/libratbag/issues/1172#issuecomment-835151702 Probably the same issue here.

**Comment by enkore** [comment]
The driver in libratbag for these is actually based on this tool :)

libratbag is really the correct place for that

**Comment by korkje** [comment]
Should anyone come across this, I've created a cross platform [CLI tool for Model O Wireless](https://github.com/korkje/mow), feel free to clone and use as you like!
