### ISSUE TITLE
building fails

### ISSUE THREAD

**Issue by arrayffs** [enkore/gloriousctl#6]
Could someone help me out? when i do 
`make gloriousctl`
it gives me this error:
gcc -Wall -Wextra gloriousctl.c -lhidapi-hidraw -o gloriousctl -g
gloriousctl.c:10:10: fatal error: hidapi/hidapi.h: No such file or directory
   10 | #include <hidapi/hidapi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:5: gloriousctl] Error 1

please help me

**Comment by enkore** [comment]
You need to install hidapi, package name depends on distro but should be something like `hidapi`, `libhidapi`, `libhidapi-hidraw`
