### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by clintisclint** [enkore/gloriousctl#8]
Hello, im a newbie to github. How do I install this program? I'm currently using Linux Arch gui version.

**Comment by enkore** [comment]
You'd need to install `base-devel hidapi git` (`pacman -S base-devel ...`) then clone this repo and run `make` then `sudo make install`.

Or, **what I would recommend instead**, install `piper` with pacman, which is a GUI tool.

**Comment by clintisclint** [comment]
Hey i'm super super sorry to disturb you but how can I do the things you told me to do? I'm very new to arch linux and I mainly installed it for the performance. I want to use this program so I can change my debounce time on my glorious model o wired. I just installed piper but it didn't have a debounce time slider. I'm very sorry for disturbing you guys.
